version: "3.7"
services:
  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "MyWs12!@"
      MARIADB_MAX_ALLOWED_PACKET: 1G
      MARIADB_INNODB_LOG_FILE_SIZE: 64M
      MARIADB_character-set-server: utf8mb4
      MARIADB_CHARACTER_SET_SERVER: utf8mb4
      MARIADB_COLLATION_SERVER: utf8mb4_unicode_ci
    volumes:
      - ./database:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: "MyWs12!@"
    ports:
      - 8082:80
  httpd:
    build: ./httpd
    volumes:
      - "./htdocs:/htdocs"
    ports:
      - 8081:80
  php:
    build: ./php
    volumes:
      - "./htdocs:/htdocs"
  nginx:
    image: nginx
    volumes:
      - "./static:/usr/share/nginx/html"
    ports:
      - 8083:80
  